import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class Style {
  static const systemblue =  Color(0xFFED2736);
  static const greycolor=   Colors.grey;
  static const whitecolor=   Colors.white;
  static const blackcolor=   Colors.black;
  static const backgroundwhite=  Colors.white;
  static const headerText = TextStyle(color: systemblue, fontSize: 28, fontWeight: FontWeight.w700);
  static const normalText = TextStyle(color: Colors.white, fontWeight: FontWeight.bold);
  static TextStyle mainheading  =  GoogleFonts.poppins(color: Colors.black, fontSize: 19, fontWeight: FontWeight.w600);
  static TextStyle text  =   GoogleFonts.poppins(color: Colors.black, fontSize: 13, fontWeight: FontWeight.w600);
  static TextStyle grab  =   GoogleFonts.poppins(color: Colors.black, fontSize: 12, fontWeight: FontWeight.w500);
  static TextStyle text1  =  GoogleFonts.poppins(color: Colors.white, fontSize: 13, fontWeight: FontWeight.w600);
  static TextStyle text111  =  GoogleFonts.poppins(color: Colors.white, fontSize: 13, fontWeight: FontWeight.w500);
  static TextStyle text2  =  GoogleFonts.poppins(color: Colors.black, fontSize: 13, fontWeight: FontWeight.w500);
  static TextStyle text3  =  GoogleFonts.poppins(color: Colors.black, fontSize: 13, );
  static TextStyle text4  =  GoogleFonts.poppins(color: Colors.black, fontSize: 17,height: 1.2,fontWeight: FontWeight.w600 );
  static TextStyle text41  =  GoogleFonts.poppins(color: Colors.white, fontSize: 17,height: 1.2,fontWeight: FontWeight.w600 );
  static TextStyle text411  =  GoogleFonts.poppins(color: Colors.white, fontSize: 17,fontWeight: FontWeight.w500 );
  static TextStyle text4111  =  GoogleFonts.poppins(color: Colors.grey, fontSize: 17,fontWeight: FontWeight.w500 );
  static TextStyle text5  =  GoogleFonts.poppins(color: Colors.black, fontSize: 11,fontWeight: FontWeight.w600);
  static TextStyle text51  =  GoogleFonts.poppins(color: Colors.white, fontSize: 11,fontWeight: FontWeight.w600);
  static TextStyle text511  =  GoogleFonts.poppins(color: Colors.white, fontSize: 12,fontWeight: FontWeight.w500);
  static TextStyle text5111  =  GoogleFonts.poppins(color: Colors.white, fontSize: 10,fontWeight: FontWeight.w500);
  static TextStyle text6  =  GoogleFonts.poppins(color: Colors.white, fontSize: 10,fontWeight: FontWeight.w500);
  static TextStyle text7  =  GoogleFonts.poppins(color: Colors.black, fontSize: 15,fontWeight: FontWeight.w600);
  static TextStyle text8  =  GoogleFonts.poppins(color: Colors.white, fontSize: 11,fontWeight: FontWeight.w500);
  static TextStyle text9  =  GoogleFonts.poppins(color: Colors.white, fontSize: 14,fontWeight: FontWeight.w600);
  static TextStyle text91  =  GoogleFonts.poppins(color: Colors.black, fontSize: 14,fontWeight: FontWeight.w600);
  static TextStyle text911  =  GoogleFonts.poppins(color: Colors.black, fontSize: 14,fontWeight: FontWeight.w500);
  static TextStyle text9111  =  GoogleFonts.poppins(color: Colors.grey, fontSize: 14,fontWeight: FontWeight.w500);
  static TextStyle text91111  =  GoogleFonts.poppins(color: Colors.white, fontSize: 14,fontWeight: FontWeight.w500);
  static TextStyle text10  =  GoogleFonts.poppins(color: Colors.black, fontSize: 22,fontWeight: FontWeight.w600);
  static TextStyle text101  =  GoogleFonts.poppins(color: Colors.white, fontSize: 22,fontWeight: FontWeight.w600);
  static TextStyle text11  =  GoogleFonts.poppins(color: Colors.black, fontSize: 20,fontWeight: FontWeight.w600);
  static TextStyle text12  =  GoogleFonts.poppins(fontSize: 15, color: Colors.blue, fontWeight: FontWeight.w500);
  static TextStyle text13  =   GoogleFonts.poppins(fontSize: 10, color: Style.greycolor, fontWeight: FontWeight.w500);
  static TextStyle text14  =   GoogleFonts.poppins(fontSize: 13, color: Style.greycolor, fontWeight: FontWeight.w500);
  static TextStyle text15  =   GoogleFonts.poppins(color: Colors.white, fontSize: 19, fontWeight: FontWeight.w600);
  static TextStyle text151  =   GoogleFonts.poppins(color: Colors.black, fontSize: 19, fontWeight: FontWeight.w600);
  static TextStyle text16  =   GoogleFonts.poppins(fontSize: 25, height: 1.2, color: Style.whitecolor, fontWeight: FontWeight.w600,);
  static TextStyle text17  =    GoogleFonts.poppins(color: Colors.black54, fontSize: 19, fontWeight: FontWeight.w600);
  static TextStyle text18  =    GoogleFonts.poppins(color: Colors.white, fontSize: 19, fontWeight: FontWeight.w600);
  static TextStyle text19  =     GoogleFonts.poppins(fontSize: 30, color: Style.blackcolor, fontWeight: FontWeight.w500);
  static TextStyle text20  =    GoogleFonts.poppins(fontSize: 22, color: Style.blackcolor, fontWeight: FontWeight.w500);
  static TextStyle text201  =    GoogleFonts.poppins(fontSize: 22, color: Style.blackcolor, fontWeight: FontWeight.w600);
  static TextStyle text21  =     GoogleFonts.poppins(fontSize: 14, height: 2, color: Style.greycolor, fontWeight: FontWeight.w500);
  static TextStyle text22  =     GoogleFonts.poppins(fontSize: 16, color:Style.whitecolor, fontWeight: FontWeight.w600);
  static TextStyle text23  =     GoogleFonts.poppins(fontSize: 12, color:Style.blackcolor, fontWeight: FontWeight.w600);
  static TextStyle text24  =      GoogleFonts.poppins(fontSize: 12, color: Style.systemblue, fontWeight: FontWeight.w600);
  static TextStyle text25  =       GoogleFonts.poppins(fontSize: 16, color: Style.whitecolor, fontWeight: FontWeight.w600);
  static TextStyle text26  =       GoogleFonts.poppins(fontSize: 15, color: Style.whitecolor, fontWeight: FontWeight.w600);
  static TextStyle text27  =       GoogleFonts.poppins(fontSize: 12, color: Style.greycolor, fontWeight: FontWeight.w500);
  static TextStyle text28  =  GoogleFonts.poppins(color: Colors.white, fontSize: 14,fontWeight: FontWeight.w500);
  static TextStyle text29  =  GoogleFonts.poppins(color: Colors.black, fontSize: 15,fontWeight: FontWeight.w600);
  static TextStyle text30  =  GoogleFonts.poppins(color: systemblue, fontSize: 15,fontWeight: FontWeight.w600);
  static TextStyle text31  =  GoogleFonts.poppins(fontSize: 15,fontWeight: FontWeight.w600);
  static TextStyle text32  =  GoogleFonts.poppins(fontSize: 14,height: 2,color: blackcolor,fontWeight: FontWeight.w500);
  static TextStyle subheading  =  GoogleFonts.poppins(color: Colors.white, fontSize: 19, fontWeight: FontWeight.w600);
}

class Pods{
  static const LEFT_PADDING = EdgeInsets.only(left: 10);
  static const LEFT_WIDE_PADDING = EdgeInsets.only(left: 15);
  static const TOP_PADDING = EdgeInsets.only(top: 10);
  static const TOP_SMALL_PADDING = EdgeInsets.only(top: 5);
  static const RIGHT_PADDING = EdgeInsets.only(top: 10);
  static const HEADING_PADDING =EdgeInsets.only(left: 10,bottom: 15,top: 20);
}
